const fs = require('fs');
const path = require('path');

// Path to the autogenerated file
const filePath = path.join(__dirname, './src/models/data-contracts.ts');

// Read the file content
fs.readFile(filePath, 'utf8', (err, data) => {
  if (err) {
    console.error('Error reading the file:', err);
    return;
  }

  // Find the line with the type definition and add "export"
  const updatedContent = data.replace(/type UtilRequiredKeys/g, 'export type UtilRequiredKeys');

  // Write the updated content back to the file
  fs.writeFile(filePath, updatedContent, 'utf8', (err) => {
    if (err) {
      console.error('Error writing the file:', err);
      return;
    }
    console.log('File updated successfully with export');
  });
});