version: 2

updates:
  # ---------- /packages/client ----------
  # Weekly: group all minor/patch into one PR (to main)
  - package-ecosystem: npm
    directory: /packages/client
    schedule: { interval: weekly, day: monday, time: "07:00", timezone: Europe/Copenhagen }
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
    # keep majors out of the weekly run
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: ["dependencies"]
    commit-message: { prefix: "deps(client)", include: scope }

  # Monthly: only majors, grouped into a single PR per month (to a majors branch)
  - package-ecosystem: npm
    directory: /packages/client
    target-branch: deps/majors-client            # <— unique combo, no collision
    schedule: { interval: monthly, time: "07:00", timezone: Europe/Copenhagen }
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
    # accept only majors here
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    groups:
      major-only:
        patterns: ["*"]
        update-types: ["major"]
    labels: ["dependencies"]
    commit-message: { prefix: "deps(client:major)", include: scope }

  # ---------- /packages/integrations ----------
  # Weekly: group all minor/patch into one PR (to main)
  - package-ecosystem: npm
    directory: /packages/integrations
    schedule: { interval: weekly, day: monday, time: "07:00", timezone: Europe/Copenhagen }
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: ["dependencies"]
    commit-message: { prefix: "deps(integrations)", include: scope }

  # Monthly: only majors, grouped (to a majors branch)
  - package-ecosystem: npm
    directory: /packages/integrations
    target-branch: deps/majors-integrations      # <— unique combo
    schedule: { interval: monthly, time: "07:00", timezone: Europe/Copenhagen }
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    groups:
      major-only:
        patterns: ["*"]
        update-types: ["major"]
    labels: ["dependencies"]
    commit-message: { prefix: "deps(integrations:major)", include: scope }

  # ---------- GitHub Actions ----------
  # Weekly: group all minor/patch (to main)
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly, day: monday, time: "07:00", timezone: Europe/Copenhagen }
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: ["dependencies"]

  # Monthly: only majors, grouped (to a majors branch)
  - package-ecosystem: github-actions
    directory: /
    target-branch: deps/majors-actions           # <— unique combo
    schedule: { interval: monthly, time: "07:00", timezone: Europe/Copenhagen }
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    groups:
      major-only:
        patterns: ["*"]
        update-types: ["major"]
    labels: ["dependencies"]
