# .github/dependabot.yml
version: 2

updates:
  # /packages/client — 1 PR for all minor/patch; majors separate
  - package-ecosystem: "npm"
    directory: "/packages/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Copenhagen"
    versioning-strategy: increase-if-necessary
    # allow room for separate major PRs alongside the grouped one
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: ["dependencies"]
    commit-message:
      prefix: "deps(client)"
      include: "scope"

  # /packages/integrations — 1 PR for all minor/patch; majors separate
  - package-ecosystem: "npm"
    directory: "/packages/integrations"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Copenhagen"
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: ["dependencies"]
    commit-message:
      prefix: "deps(integrations)"
      include: "scope"

  # GitHub Actions — 1 PR for all minor/patch; majors separate
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: ["dependencies"]
