name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  node-version: '16'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
      - run: npm run gen-api 
      - run: npm run build
      - run: npm run build:types
      - run: npm test
        name: Unit tests
      - run: npm run integration-test --DATASET_ID=${{env.DATASET_ID}}
        env:
          DATASET_ID: ${{secrets.INTEGRATIONTESTS_DATASET_ID}}
          API_KEY: ${{secrets.INTEGRATIONTESTS_API_KEY}}
        name: Integration tests