name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  node-version: '18'

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
        name: Install dependencies
      - run: npm run gen-api 
        name: Generate API type defs
      - run: npm run build
        name: Build
      - run: npm run build:types
        name: Build Types
      - run: npm test
        name: Unit tests
      - run: npm run integration-test
        env:
          npm_config_DATASET_ID: ${{secrets.INTEGRATIONTESTS_DATASET_ID}}
          npm_config_API_KEY: ${{secrets.INTEGRATIONTESTS_API_KEY}}
          npm_config_SERVER_URL: ${{secrets.INTEGRATIONTESTS_SERVER_URL}}
        name: Integration tests
  
  test-integrations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/integrations
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build
      - run: npm test
        name: Unit tests
      - run: npm run integration-test
        env:
          npm_config_DATASET_ID: ${{secrets.INTEGRATIONTESTS_DATASET_ID}}
          npm_config_API_KEY: ${{secrets.INTEGRATIONTESTS_API_KEY}}
          npm_config_SERVER_URL: ${{secrets.INTEGRATIONTESTS_SERVER_URL}}
        name: Integration tests