name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  node-version: '16'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - run: |
          npm ci
          npm run gen-api 
          npm run build
          npm run build:types

  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Unit tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - run: |
          npm test